version: 1
frontend:
  phases:
    preBuild:
      commands:
        # Download and install Hugo Extended
        - wget https://github.com/gohugoio/hugo/releases/download/v0.121.0/hugo_extended_0.121.0_Linux-64bit.tar.gz
        - tar -xf hugo_extended_0.121.0_Linux-64bit.tar.gz
        - mv hugo /usr/bin/hugo
        - rm -rf hugo_extended_0.121.0_Linux-64bit.tar.gz
        - hugo version
    build:
      commands:
        # Build the Hugo site
        - hugo --minify
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
